FROM ubuntu:20.04 AS ubuntu-tisdk1
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
RUN \
    apt update && apt upgrade -y \
    && apt install -y --no-install-recommends \
    wget \
    ca-certificates \
    && echo .
    #&& rm -rf /var/lib/apt/lists/*

WORKDIR /opt
RUN echo . \
    && wget https://software-dl.ti.com/jacinto7/esd/processor-sdk-rtos-jacinto7/08_01_00_11/exports/ti-processor-sdk-rtos-j721e-evm-08_01_00_11.tar.gz \
    && wget https://software-dl.ti.com/jacinto7/esd/processor-sdk-linux-jacinto7/08_01_00_07/exports/ti-processor-sdk-linux-j7-evm-08_01_00_07-Linux-x86-Install.bin \
    && echo .

RUN echo . \
    && chmod +x ./ti-processor-sdk-linux-j7-evm-08_01_00_07-Linux-x86-Install.bin \
    && ./ti-processor-sdk-linux-j7-evm-08_01_00_07-Linux-x86-Install.bin \
    && echo .

RUN echo . \
    && tar xzf ti-processor-sdk-rtos-j721e-evm-08_01_00_11.tar.gz \
    && echo .

RUN echo .\
    && apt install -y --no-install-recommends \
    xz-utils \
    && echo .

WORKDIR /opt/ti-processor-sdk-rtos-j721e-evm-08_01_00_11
RUN echo . \
    && ln -s /opt/ti-processor-sdk-linux-j7-evm-08_01_00_07/board-support/prebuilt-images/boot-j7-evm.tar.gz \
    && ln -s /opt/ti-processor-sdk-linux-j7-evm-08_01_00_07/filesystem/tisdk-default-image-j7-evm.tar.xz \
    && echo .

WORKDIR /opt/ti-processor-sdk-rtos-j721e-evm-08_01_00_11/psdk_rtos
RUN echo . \
    && ln -sf $PWD/j7_c_models/lib/PC/x86_64/LINUX/release/libDOF.so /usr/lib/x86_64-linux-gnu/libDOF.so \
    && ln -sf $PWD/j7_c_models/lib/PC/x86_64/LINUX/release/libglbce.so /usr/lib/x86_64-linux-gnu/libApicalSIM.so.1 \
    && dpkg --add-architecture i386 \
    && apt update && apt upgrade -y \
    && apt install -y --no-install-recommends \
    gcc-7 \
    g++-7 \
    libpng-dev \
    zlib1g-dev \
    libtiff-dev \
    libsdl2-dev \
    libsdl2-image-dev \
    graphviz \
    graphviz-dev \
    build-essential \
    libxmu-dev \
    libxi-dev \
    libgl-dev \
    libosmesa-dev \
    python3 \
    python3-pip \
    curl \
    libz1:i386 \
    libc6-dev-i386 \
    libc6:i386 \
    libstdc++6:i386 \
    g++-multilib \
    git \
    diffstat \
    texinfo \
    gawk \
    chrpath \
    libfreetype6-dev \
    mono-runtime \
    flex \
    libssl-dev \
    u-boot-tools \
    libdevil-dev \
    bison \
    python3-pyelftools \
    python3-dev \
    libx11-dev \
    && echo .

WORKDIR /opt/ti-processor-sdk-rtos-j721e-evm-08_01_00_11
RUN echo . \
    && apt update && apt upgrade -y \
    && apt install -y --no-install-recommends \
    unzip \
    && echo .

WORKDIR /opt/ti-processor-sdk-rtos-j721e-evm-08_01_00_11
RUN echo . \
    && /bin/bash ./psdk_rtos/scripts/setup_psdk_rtos.sh --skip_sudo \
    && echo .

WORKDIR /opt/ti-processor-sdk-rtos-j721e-evm-08_01_00_11
RUN echo . \
    && cd glew-2.0.0 \
    && make install \
    && echo .

WORKDIR /opt/ti-processor-sdk-rtos-j721e-evm-08_01_00_11
RUN echo . \
    && /bin/bash ./psdk_rtos/scripts/setup_psdk_rtos.sh --skip_sudo \
    && echo .

WORKDIR /opt/ti-processor-sdk-rtos-j721e-evm-08_01_00_11
RUN echo . \
    && apt update && apt upgrade -y \
    && apt install -y --no-install-recommends \
    libncurses5 \
    && echo .

WORKDIR /opt/ti-processor-sdk-rtos-j721e-evm-08_01_00_11
RUN echo . \
    && echo "BUILD_EMULATION=no" >> tiovx/build_flags.mak \
    && echo "BUILD_TARGET_MODE=yes" >> tiovx/build_flags.mak \
    && echo "BUILD_LINUX_A72=yes" >> tiovx/build_flags.mak \
    && echo "PROFILE=release" >> tiovx/build_flags.mak \
    && cd vision_apps \
    && make vision_apps -j2 \
    && echo .

FROM ubuntu-tisdk1 AS ubuntu-tiros-foxy
ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=foxy

WORKDIR /opt
RUN git clone --single-branch --depth 1 --branch REL.08.01.00.03 git://git.ti.com/processor-sdk-vision/jacinto_ros_perception

