[[support-information]]
== Support Information

All support for this design is through BeagleBoard.org community at:

link:https://forum.beagleboard.org/[BeagleBoard.org fourm].


[[hardware-design]]
=== Hardware Design

#Update required#

You can find all BBAI-64 hardware files https://git.beagleboard.org/beagleboard/beaglebone-ai-64/-/tree/master/hw[here].


[[software-updates]]
=== Software Updates

You can download and flash the new image onto your BBAI-64 from 
https://rcn-ee.net/rootfs/debian-arm64/[this] image repository from Robert.

#Update required#

To see what SW revision is loaded into the eMMC check `/etc/dogtag`.
It should look something like as shown below,

```
debian@BeagleBone:~$ cat /etc/dogtag 
BeagleBoard.org Debian Bullseye Xfce Image 2022-05-26
```

[[rma-support]]
=== RMA Support

#Update required#

If you feel your board is defective or has issues, request an Return Merchandise Application (RMA) by filling out the form at
http://beagleboard.org/support/rma . You will need the serial number and revision of the board. The
serial numbers and revisions keep moving. Different boards can have different locations depending
on when they were made. The following figures show the three locations of the serial and revision
number.

#TODO: Add serial number images#

[[trouble-shooting-video-output-issues]]
=== Troubleshooting video output issues

#TODO#

[[edid]]
==== EDID

EDID is the way the board requests information from the display and
determines all the resolutions that it can support. The driver on the
board will then look at these timings and find the highest resolution
that is compatible with the board and uses that resolution for the
display. For more information on EDID, you can take a look at
http://en.wikipedia.org/wiki/Extended_display_identification_data[_http://en.wikipedia.org/wiki/Extended_display_identification_data_]

If the board is not able to read the EDID, for whatever reason, it does
not have this information. A few possible reasons for this are:

* Bad cable
* Cable not plugged in all the way on both ends
* Display not powered on. (It should still work powered off, but some
displays do not).

[[display-source-selection]]
==== DISPLAY SOURCE SELECTION

One easy thing to overlook is that you need to select the display source
that matches the port you are using on the TV. Some displays may auto
select, so you may need to disconnect the other inputs until you are
sure the display works with the board.

[[out-of-sequence]]
==== OUT OF SEQUENCE

Sometimes the display and the board can get confused. One way to prevent
this is after everything is cabled up and running, you can power cycle
the display, with the board still running. You can also try resetting
the board and let it reboot to resync with the TV.

[[overscan]]
==== OVERSCAN

Some displays use what is called overscan. This can be seen in TVs and
not so much on Monitors. It causes the image to be missing on the edges,
such that you cannot see them displayed. Some higher end displays allow
you to disable overscan.

Most TVs have a mode that allows you to adjust the image. These are
options like Normal, Wide, Zoom, or Fit. Normal seems to be the best
option as it does not chop of the edges. The other ones will crop of the
edges.

[[taking-a-nap]]
==== Taking a Nap

In some cases the board can come up in a power down/screen save mode. No
display will be present. This is due to the board believing that it is
asleep. To come out of this, you will need to hit the keyboard or move
the mouse.

Once working, the board will time out and go back to sleep again. This
can cause the display to go into a power down mode as well. You may need
to turn the display back on again. Sometimes, it may take a minute or so
for the display to catch up and show the image.

[[audio]]
==== AUDIO

Audio will only work on TV resolutions. This is due to the the way the
specification was written. Some displays have built in speakers and
others require external. Make sure you have a TV resolution and speakers
are connected if they are not built in. The SW should default to a TV
resolution giving audio support. The HDMI driver should default to the
highest audio supported resolution.

[[getting-help]]
==== Getting Help

If you need some up to date troubleshooting techniques,
you can post your queries on link:https://forum.beagleboard.org/[BeagleBoard.org fourm].
