[preface]

== Preface

*BEAGLEBONE AI-64 DESIGN*

These design materials referred to in this document are 
*NOT SUPPORTED* and *DO NOT* constitute a reference design. 
Only “community” support is allowed via resources at
https://forum.beagleboard.org/[_BeagleBoard.org forum_].

THERE IS NO WARRANTY FOR THE DESIGN MATERIALS, TO THE EXTENT PERMITTED
BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT
HOLDERS AND/OR OTHER PARTIES PROVIDE THE DESIGN MATERIALS “AS IS”
WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND
THE PERFORMANCE OF THE DESIGN MATERIALS IS WITH YOU. SHOULD THE DESIGN
MATERIALS PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY
SERVICING, REPAIRING, OR CORRECTION.

This board was designed as an evaluation and development tool. It was
not designed with any other application in mind. As such, the design
materials that are provided which include schematic, BOM, and PCB files,
may or may not be suitable for any other purposes. If used, the design
material becomes your responsibility as to whether or not it meets your
specific needs or your specific applications and may require changes to
meet your requirements.

*BEAGLEBONE AI-64 ADDITIONAL TERMS*

BeagleBoard.org Foundation and logo-licensed manufacturers provide the
enclosed BeagleBone under the following conditions:

The user assumes all responsibility and liability for proper and safe
handling of the goods. Further, the user indemnifies the Supplier from all
claims arising from the handling or use of the goods.

Should BeagleBone not meet the specifications indicated in the
System Reference Manual, BeagleBone may be returned within 90 days
from the date of delivery to the distributor of purchase for a full
refund. THE FOREGOING LIMITED WARRANTY IS THE EXCLUSIVE WARRANTY MADE BY
SELLER TO BUYER AND IS IN LIEU OF ALL OTHER WARRANTIES, EXPRESSED,
IMPLIED, OR STATUTORY, INCLUDING ANY WARRANTY OF MERCHANTABILITY OR
FITNESS FOR ANY PARTICULAR PURPOSE. EXCEPT TO THE EXTENT OF THE
INDEMNITY SET FORTH ABOVE, NEITHER PARTY SHALL BE LIABLE TO THE OTHER
FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES.

Please read the System Reference Manual and, specifically, the Warnings
and Restrictions notice in the Systems Reference Manual prior to
handling the product. This notice contains important safety information
about temperatures and voltages.

No license is granted under any patent right or other intellectual
property right of Supplier covering or relating to any machine, process,
or combination in which such Supplier products or services might be or
are used. The Supplier currently deals with a variety of customers for
products, and therefore our arrangement with the user is not exclusive.
The Supplier assumes no liability for applications assistance, customer
product design, software performance, or infringement of patents or
services described herein.

*UNITED STATES FCC AND CANADA IC REGULATORY COMPLIANCE INFORMATION*

*BeagleBone is annotated to comply with Part 15 of the FCC Rules*.
Operation is subject to the following two conditions: (1) This device
may not cause harmful interference, and (2) this device must accept any
interference received, including interference that may cause undesired
operation. Changes or modifications not expressly approved by the party
responsible for compliance could void the user’s authority to operate
the equipment.

This Class A or B digital apparatus complies with Canadian ICES-003.
Changes or modifications not expressly approved by the party responsible
for compliance could void the user’s authority to operate the equipment.

*BEAGLEBONE WARNINGS, RESTRICTIONS AND DISCLAIMERS*

_For Feasibility Evaluation Only, in Laboratory/Development
Environments_. BeagleBone AI-64 is not a complete product. It is
intended solely for use for preliminary feasibility evaluation in
laboratory/development environments by technically qualified electronics
experts who are familiar with the dangers and application risks
associated with handling electrical mechanical components, systems and
subsystems. It should not be used as all or part of a finished end
product.

*Your Sole Responsibility and Risk* you acknowledge, represent, and
agree that:

1.  You have unique knowledge concerning Federal, State, and local
regulatory requirements (including but not limited to Food and Drug
Administration regulations, if applicable) which relate to your products
and which relate to your use (and/or that of your employees, affiliates,
contractors or designees) of BeagleBone for evaluation, testing and
other purposes.
2.  You have full and exclusive responsibility to assure the safety and
compliance of your products with all such laws and other applicable
regulatory requirements, and also to assure the safety of any activities
to be conducted by you and/or your employees, affiliates, contractors or
designees, using BeagleBone. Further, you are responsible to assure
that any interfaces (electronic and/or mechanical) between the
BeagleBone and any human body are designed with suitable isolation and
means to safely limit accessible leakage currents to minimize the risk
of electrical shock hazard.
3.  Since BeagleBone is not a completed product, it may not meet all
applicable regulatory and safety compliance standards which may normally
be associated with similar items. You assume full responsibility to
determine and/or assure compliance with any such standards and related
certifications as may be applicable. You will employ reasonable
safeguards to ensure that your use of BeagleBone will not result in
any property damage, injury, or death, even if BeagleBone should fail
to perform as described or expected.

*Certain Instructions*. It is important to operate BeagleBone AI-64
within Supplier’s _recommended specifications and environmental
considerations per the user guidelines._ _Exceeding the specified
BeagleBone ratings (including but not limited to input and output_
_voltage, current, power, and environmental ranges) may cause property
damage, personal_ _injury, or death. If there are questions concerning
these ratings please contact the Supplier_ _representative before
connecting interface electronics including input power and intended_
_loads. Any loads applied outside of the specified output range may
result in unintended_ _and/or inaccurate operation and/or possible
permanent damage to BeagleBone and/or_ _interface electronics.
Please consult the System Reference Manual before connecting any_
_load to BeagleBone output. If there is uncertainty as to the load
specification, please_ _contact the Supplier representative. During
normal operation, some circuit components_ _may have case temperatures
greater than 60 C as long as the input and output are_ _maintained at a
normal ambient operating temperature. These components include but are_
_not limited to linear regulators, switching transistors, pass
transistors, and current sense_ _resistors which can be identified using
BeagleBone schematic located at the link in the_ _BeagleBone System
Reference Manual. When placing measurement probes near these_ _devices
during normal operation, please be aware that these devices may be very
warm to_ _the touch. As with all electronic evaluation tools, only
qualified personnel knowledgeable in_ _electronic measurement and
diagnostics normally found in development environments_ _should use the
BeagleBone._

*Agreement to Defend, Indemnify and Hold Harmless*. You agree to defend,
indemnify'' _and hold the Suppliers, their licensors and their
representatives harmless from and against_ _any and all claims, damages,
losses, expenses, costs and liabilities (collectively,_ _"Claims")
arising out of or in connection with any use of BeagleBone that is
not in_ _accordance with the terms of the agreement. This obligation
shall apply whether Claims_ _arise under the law of tort or contract or any
other legal theory, and even if BeagleBone_ _fails to perform as
described or expected._

*Safety-Critical or Life-Critical Applications*. If you intend to
evaluate the components for possible'' _use in safety critical
applications (such as life support) where a failure of the Supplier’s
product_ _would reasonably be expected to cause severe personal injury
or death, such as devices which are_ _classified as FDA Class III or
similar classification, then you must specifically notify Suppliers of_
_such intent and enter into a separate Assurance and Indemnity
Agreement._


*Mailing Address*:

BeagleBoard.org Foundation +
4467 Ascot Ct +
Oakland Twp, MI 48306 U.S.A.

*WARRANTY:* _BeagleBone AI-64 Assembly as purchased is warranted
against defects in materials and workmanship for a period of 90 days
from purchase. This warranty does not cover any problems occurring as a
result of improper use, modifications, exposure to water, excessive
voltages, abuse, or accidents. All boards will be returned via standard
mail if an issue is found. If no issue is found or express return is
needed, the customer will pay all shipping costs_.

Before returning the board, please visit

_BeagleBoard.org/support_

For up to date SW images and technical information refer to
https://beagleboard.org/latest-images[_https://beagleboard.org/latest-images_]

All support for this board is provided via community support at
https://forum.beagleboard.org/[_BeagleBoard.org forum_]

To return a defective board for repair, please request an RMA at
https://beagleboard.org/support/rma[_beagleboard.org/support/rma_]

*Please DO NOT return the board without approval from the RMA team
first.*

All boards received without RMA approval will not be worked on.